sonar.projectKey=config-service
sonar.projectName=config-service
sonar.sources=services/config-service/src
sonar.exclusions=**/node_modules/**,**/*.test.js,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*